apiVersion: apps/v1
kind: Deployment

metadata:
  name: gudang-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: gudang-service

  template:
    metadata:
      labels:
        app: gudang-service

    spec:
      containers:
      - name: gudang-service

        image: dhiyauu/gudang-service:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: DB_HOST
          value: mysql

        - name: DB_PORT
          value: "3306"

        - name: DB_USER
          value: root

        - name: DB_PASSWORD
          value: root

        - name: DB_NAME
          value: tubesdb

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
